package com.mt.iv.common.model;

import java.util.Date;

public class VoucherScrap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher700.id
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher700.company_id
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher700.company_name
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher700.voucher_id
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    private Long voucherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher700.reason
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher700.handler_id
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    private Long handlerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher700.scrap_no
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    private String scrapNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher700.created_at
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher700.updated_at
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher700.status
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher700.id
     *
     * @return the value of voucher700.id
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher700.id
     *
     * @param id the value for voucher700.id
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher700.company_id
     *
     * @return the value of voucher700.company_id
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher700.company_id
     *
     * @param companyId the value for voucher700.company_id
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher700.company_name
     *
     * @return the value of voucher700.company_name
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher700.company_name
     *
     * @param companyName the value for voucher700.company_name
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher700.voucher_id
     *
     * @return the value of voucher700.voucher_id
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public Long getVoucherId() {
        return voucherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher700.voucher_id
     *
     * @param voucherId the value for voucher700.voucher_id
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public void setVoucherId(Long voucherId) {
        this.voucherId = voucherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher700.reason
     *
     * @return the value of voucher700.reason
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher700.reason
     *
     * @param reason the value for voucher700.reason
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher700.handler_id
     *
     * @return the value of voucher700.handler_id
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public Long getHandlerId() {
        return handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher700.handler_id
     *
     * @param handlerId the value for voucher700.handler_id
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public void setHandlerId(Long handlerId) {
        this.handlerId = handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher700.scrap_no
     *
     * @return the value of voucher700.scrap_no
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public String getScrapNo() {
        return scrapNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher700.scrap_no
     *
     * @param scrapNo the value for voucher700.scrap_no
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public void setScrapNo(String scrapNo) {
        this.scrapNo = scrapNo == null ? null : scrapNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher700.created_at
     *
     * @return the value of voucher700.created_at
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher700.created_at
     *
     * @param createdAt the value for voucher700.created_at
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher700.updated_at
     *
     * @return the value of voucher700.updated_at
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher700.updated_at
     *
     * @param updatedAt the value for voucher700.updated_at
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher700.status
     *
     * @return the value of voucher700.status
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher700.status
     *
     * @param status the value for voucher700.status
     *
     * @mbggenerated Fri Dec 01 08:38:32 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}