package com.mt.pc.common.model;

import java.math.BigDecimal;
import java.util.Date;

public class PcInquirySupSub {

    private Long id;

    private Long inquirySupId;

    private String matId;

    private String matNo;

    private String matDesc;

    private Long matTypeId;

    private String matTypeName;

    private String matModel;

    private BigDecimal quantity;

    private BigDecimal processUp;

    private BigDecimal processCost;

    private BigDecimal up;

    private String taxCost;

    private BigDecimal totalPrice;

    private Date createdAt;

    private Date updatedAt;

    private Byte status;

    private  PcInquirySup  pcInquirySup;

    public PcInquirySup getPcInquirySup() {
        return pcInquirySup;
    }
    public void setPcInquirySup(PcInquirySup pcInquirySup) {
        this.pcInquirySup = pcInquirySup;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getInquirySupId() {
        return inquirySupId;
    }

    public void setInquirySupId(Long inquirySupId) {
        this.inquirySupId = inquirySupId;
    }

    public String getMatId() {
        return matId;
    }

    public void setMatId(String matId) {
        this.matId = matId == null ? null : matId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup_sub.mat_no
     *
     * @return the value of pc_inquiry_sup_sub.mat_no
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public String getMatNo() {
        return matNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup_sub.mat_no
     *
     * @param matNo the value for pc_inquiry_sup_sub.mat_no
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public void setMatNo(String matNo) {
        this.matNo = matNo == null ? null : matNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup_sub.mat_desc
     *
     * @return the value of pc_inquiry_sup_sub.mat_desc
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public String getMatDesc() {
        return matDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup_sub.mat_desc
     *
     * @param matDesc the value for pc_inquiry_sup_sub.mat_desc
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public void setMatDesc(String matDesc) {
        this.matDesc = matDesc == null ? null : matDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup_sub.mat_type_id
     *
     * @return the value of pc_inquiry_sup_sub.mat_type_id
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public Long getMatTypeId() {
        return matTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup_sub.mat_type_id
     *
     * @param matTypeId the value for pc_inquiry_sup_sub.mat_type_id
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public void setMatTypeId(Long matTypeId) {
        this.matTypeId = matTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup_sub.mat_type_name
     *
     * @return the value of pc_inquiry_sup_sub.mat_type_name
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public String getMatTypeName() {
        return matTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup_sub.mat_type_name
     *
     * @param matTypeName the value for pc_inquiry_sup_sub.mat_type_name
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public void setMatTypeName(String matTypeName) {
        this.matTypeName = matTypeName == null ? null : matTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup_sub.mat_model
     *
     * @return the value of pc_inquiry_sup_sub.mat_model
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public String getMatModel() {
        return matModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup_sub.mat_model
     *
     * @param matModel the value for pc_inquiry_sup_sub.mat_model
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public void setMatModel(String matModel) {
        this.matModel = matModel == null ? null : matModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup_sub.quantity
     *
     * @return the value of pc_inquiry_sup_sub.quantity
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup_sub.quantity
     *
     * @param quantity the value for pc_inquiry_sup_sub.quantity
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup_sub.process_up
     *
     * @return the value of pc_inquiry_sup_sub.process_up
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public BigDecimal getProcessUp() {
        return processUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup_sub.process_up
     *
     * @param processUp the value for pc_inquiry_sup_sub.process_up
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public void setProcessUp(BigDecimal processUp) {
        this.processUp = processUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup_sub.process_cost
     *
     * @return the value of pc_inquiry_sup_sub.process_cost
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public BigDecimal getProcessCost() {
        return processCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup_sub.process_cost
     *
     * @param processCost the value for pc_inquiry_sup_sub.process_cost
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public void setProcessCost(BigDecimal processCost) {
        this.processCost = processCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup_sub.up
     *
     * @return the value of pc_inquiry_sup_sub.up
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public BigDecimal getUp() {
        return up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup_sub.up
     *
     * @param up the value for pc_inquiry_sup_sub.up
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public void setUp(BigDecimal up) {
        this.up = up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup_sub.tax_cost
     *
     * @return the value of pc_inquiry_sup_sub.tax_cost
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public String getTaxCost() {
        return taxCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup_sub.tax_cost
     *
     * @param taxCost the value for pc_inquiry_sup_sub.tax_cost
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public void setTaxCost(String taxCost) {
        this.taxCost = taxCost == null ? null : taxCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup_sub.total_price
     *
     * @return the value of pc_inquiry_sup_sub.total_price
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup_sub.total_price
     *
     * @param totalPrice the value for pc_inquiry_sup_sub.total_price
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup_sub.created_at
     *
     * @return the value of pc_inquiry_sup_sub.created_at
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup_sub.created_at
     *
     * @param createdAt the value for pc_inquiry_sup_sub.created_at
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup_sub.updated_at
     *
     * @return the value of pc_inquiry_sup_sub.updated_at
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup_sub.updated_at
     *
     * @param updatedAt the value for pc_inquiry_sup_sub.updated_at
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup_sub.status
     *
     * @return the value of pc_inquiry_sup_sub.status
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup_sub.status
     *
     * @param status the value for pc_inquiry_sup_sub.status
     *
     * @mbggenerated Fri Nov 17 16:13:56 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}