package com.mt.pc.common.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PcInquirySup {

    private Long id;

    private Long supCompanyId;

    private String supName;

    private Byte dealFlag;

    private Long inquiryId;

    private Integer companyId;

    private String companyName;

    private Long purchMan;

    private String purchManName;

    private String purchManPhone;

    private String purchManEmail;

    private Date inquiryDate;

    private Date quoteDate;

    private Date quoteEndDate;

    private Date deliveryDate;

    private String deliveryPlace;

    private String coin;

    private Byte invoiceType;

    private BigDecimal taxRatio;

    private Long handlerId;

    private Date createdAt;

    private Date updatedAt;

    private BigDecimal totalPrice;

    private Byte status;

    private String remark;

    private List<PcInquirySupSub>    details=new ArrayList<PcInquirySupSub>();

    public List<PcInquirySupSub> getDetails() {
        return details;
    }
    public void setDetails(List<PcInquirySupSub> details) {
        this.details = details;
    }

    public Long getId() {
        return id;
    }


    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.sup_company_id
     *
     * @return the value of pc_inquiry_sup.sup_company_id
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public Long getSupCompanyId() {
        return supCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.sup_company_id
     *
     * @param supCompanyId the value for pc_inquiry_sup.sup_company_id
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setSupCompanyId(Long supCompanyId) {
        this.supCompanyId = supCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.sup_name
     *
     * @return the value of pc_inquiry_sup.sup_name
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public String getSupName() {
        return supName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.sup_name
     *
     * @param supName the value for pc_inquiry_sup.sup_name
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setSupName(String supName) {
        this.supName = supName == null ? null : supName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.deal_flag
     *
     * @return the value of pc_inquiry_sup.deal_flag
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public Byte getDealFlag() {
        return dealFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.deal_flag
     *
     * @param dealFlag the value for pc_inquiry_sup.deal_flag
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setDealFlag(Byte dealFlag) {
        this.dealFlag = dealFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.inquiry_id
     *
     * @return the value of pc_inquiry_sup.inquiry_id
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public Long getInquiryId() {
        return inquiryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.inquiry_id
     *
     * @param inquiryId the value for pc_inquiry_sup.inquiry_id
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setInquiryId(Long inquiryId) {
        this.inquiryId = inquiryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.company_id
     *
     * @return the value of pc_inquiry_sup.company_id
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.company_id
     *
     * @param companyId the value for pc_inquiry_sup.company_id
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.company_name
     *
     * @return the value of pc_inquiry_sup.company_name
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.company_name
     *
     * @param companyName the value for pc_inquiry_sup.company_name
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.purch_man
     *
     * @return the value of pc_inquiry_sup.purch_man
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public Long getPurchMan() {
        return purchMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.purch_man
     *
     * @param purchMan the value for pc_inquiry_sup.purch_man
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setPurchMan(Long purchMan) {
        this.purchMan = purchMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.purch_man_name
     *
     * @return the value of pc_inquiry_sup.purch_man_name
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public String getPurchManName() {
        return purchManName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.purch_man_name
     *
     * @param purchManName the value for pc_inquiry_sup.purch_man_name
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setPurchManName(String purchManName) {
        this.purchManName = purchManName == null ? null : purchManName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.purch_man_phone
     *
     * @return the value of pc_inquiry_sup.purch_man_phone
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public String getPurchManPhone() {
        return purchManPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.purch_man_phone
     *
     * @param purchManPhone the value for pc_inquiry_sup.purch_man_phone
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setPurchManPhone(String purchManPhone) {
        this.purchManPhone = purchManPhone == null ? null : purchManPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.purch_man_email
     *
     * @return the value of pc_inquiry_sup.purch_man_email
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public String getPurchManEmail() {
        return purchManEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.purch_man_email
     *
     * @param purchManEmail the value for pc_inquiry_sup.purch_man_email
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setPurchManEmail(String purchManEmail) {
        this.purchManEmail = purchManEmail == null ? null : purchManEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.inquiry_date
     *
     * @return the value of pc_inquiry_sup.inquiry_date
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public Date getInquiryDate() {
        return inquiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.inquiry_date
     *
     * @param inquiryDate the value for pc_inquiry_sup.inquiry_date
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setInquiryDate(Date inquiryDate) {
        this.inquiryDate = inquiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.quote_date
     *
     * @return the value of pc_inquiry_sup.quote_date
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public Date getQuoteDate() {
        return quoteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.quote_date
     *
     * @param quoteDate the value for pc_inquiry_sup.quote_date
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setQuoteDate(Date quoteDate) {
        this.quoteDate = quoteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.quote_end_date
     *
     * @return the value of pc_inquiry_sup.quote_end_date
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public Date getQuoteEndDate() {
        return quoteEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.quote_end_date
     *
     * @param quoteEndDate the value for pc_inquiry_sup.quote_end_date
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setQuoteEndDate(Date quoteEndDate) {
        this.quoteEndDate = quoteEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.delivery_date
     *
     * @return the value of pc_inquiry_sup.delivery_date
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public Date getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.delivery_date
     *
     * @param deliveryDate the value for pc_inquiry_sup.delivery_date
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.delivery_place
     *
     * @return the value of pc_inquiry_sup.delivery_place
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public String getDeliveryPlace() {
        return deliveryPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.delivery_place
     *
     * @param deliveryPlace the value for pc_inquiry_sup.delivery_place
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setDeliveryPlace(String deliveryPlace) {
        this.deliveryPlace = deliveryPlace == null ? null : deliveryPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.coin
     *
     * @return the value of pc_inquiry_sup.coin
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public String getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.coin
     *
     * @param coin the value for pc_inquiry_sup.coin
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setCoin(String coin) {
        this.coin = coin == null ? null : coin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.invoice_type
     *
     * @return the value of pc_inquiry_sup.invoice_type
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public Byte getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.invoice_type
     *
     * @param invoiceType the value for pc_inquiry_sup.invoice_type
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setInvoiceType(Byte invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.tax_ratio
     *
     * @return the value of pc_inquiry_sup.tax_ratio
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public BigDecimal getTaxRatio() {
        return taxRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.tax_ratio
     *
     * @param taxRatio the value for pc_inquiry_sup.tax_ratio
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setTaxRatio(BigDecimal taxRatio) {
        this.taxRatio = taxRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.handler_id
     *
     * @return the value of pc_inquiry_sup.handler_id
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public Long getHandlerId() {
        return handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.handler_id
     *
     * @param handlerId the value for pc_inquiry_sup.handler_id
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setHandlerId(Long handlerId) {
        this.handlerId = handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.created_at
     *
     * @return the value of pc_inquiry_sup.created_at
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.created_at
     *
     * @param createdAt the value for pc_inquiry_sup.created_at
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.updated_at
     *
     * @return the value of pc_inquiry_sup.updated_at
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.updated_at
     *
     * @param updatedAt the value for pc_inquiry_sup.updated_at
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.total_price
     *
     * @return the value of pc_inquiry_sup.total_price
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.total_price
     *
     * @param totalPrice the value for pc_inquiry_sup.total_price
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.status
     *
     * @return the value of pc_inquiry_sup.status
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.status
     *
     * @param status the value for pc_inquiry_sup.status
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_inquiry_sup.remark
     *
     * @return the value of pc_inquiry_sup.remark
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_inquiry_sup.remark
     *
     * @param remark the value for pc_inquiry_sup.remark
     *
     * @mbggenerated Fri Nov 17 16:04:52 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}